### ISSUE TITLE
-SOLVED AFTER UNINSTALL & REINSTALL of the 3 mentioned mods- The game won't load

### ISSUE THREAD

**Issue by Wolfy339** [microsoftenator2022/HomebrewWarlock#1]
Hi, I installed the mod but the game won't load on the main screen.

- MiscTweaksAndFixes2 UPDATED + Homebrew Warlock = game won't load
- MiscTweaksAndFixes2 UPDATED + NO homebrew Warlock = game won't load
- MiscTweaksAndFixes2 the version before + Homebrew Warlock = game won't load
- MiscTweaksAndFixes2 the version before only = works fine

EDIT: Removing alternate human traits solved the issue. 
MiscTweaksAndFixes2 UPDATED + Homebrew Warlock + REMOVING alternate human traits = game works.

**Comment by microsoftenator2022** [comment]
Can you attach your Player.log?
I will also be releasing an update to Alternate Human Traits, once 1.0 of this mod is done.

**Comment by Wolfy339** [comment]
I will reinstall it and post the log.
EDIT: after reinstall, it seems to work, no idea why. I apologize.
